server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portal
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    generate:
      ddl-auto: true

